// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVESS_H
#define DRIVESS_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveSS: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<SpeedController> frontleft;
	std::shared_ptr<SpeedController> frontright;
	std::shared_ptr<SpeedController> backleft;
	std::shared_ptr<SpeedController> backright;
	std::shared_ptr<RobotDrive> robotDrive;
	std::shared_ptr<AnalogGyro> gyro;
	static constexpr float kP = 0.03f;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	DriveSS();
	void InitDefaultCommand();
	unsigned long begTime;
	void start();
	void main();
	void Stop();
	unsigned long elapsedTime();
	void TankDrive(Joystick left, Joystick right);
	void wait(int seconds);
	float angle;
	void CountDown();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
