// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<SpeedController> RobotMap::driveSSfrontleft;
std::shared_ptr<SpeedController> RobotMap::driveSSfrontright;
std::shared_ptr<SpeedController> RobotMap::driveSSbackleft;
std::shared_ptr<SpeedController> RobotMap::driveSSbackright;
std::shared_ptr<RobotDrive> RobotMap::driveSSRobotDrive;
std::shared_ptr<AnalogGyro> RobotMap::driveSSGyro;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    driveSSfrontleft.reset(new Talon(0));
    lw->AddActuator("DriveSS", "frontleft", std::static_pointer_cast<Talon>(driveSSfrontleft));
    
    driveSSfrontright.reset(new Talon(1));
    lw->AddActuator("DriveSS", "frontright", std::static_pointer_cast<Talon>(driveSSfrontright));
    
    driveSSbackleft.reset(new Talon(2));
    lw->AddActuator("DriveSS", "backleft", std::static_pointer_cast<Talon>(driveSSbackleft));
    
    driveSSbackright.reset(new Talon(3));
    lw->AddActuator("DriveSS", "backright", std::static_pointer_cast<Talon>(driveSSbackright));
    
    driveSSRobotDrive.reset(new RobotDrive(driveSSfrontleft, driveSSfrontright,
              driveSSbackleft, driveSSbackright));
    
    driveSSRobotDrive->SetSafetyEnabled(true);
        driveSSRobotDrive->SetExpiration(0.1);
        driveSSRobotDrive->SetSensitivity(0.5);
        driveSSRobotDrive->SetMaxOutput(1.0);

    driveSSGyro.reset(new AnalogGyro(0));
    lw->AddSensor("DriveSS", "Gyro", driveSSGyro);
    driveSSGyro->SetSensitivity(0.007);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
